# Generated by Django 3.1.4 on 2021-01-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
