# Generated by Django 3.1.4 on 2021-01-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_type',
            name='ac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_type',
            name='bee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_type',
            name='sc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_type',
            name='sex',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_type',
            name='total_energy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
