# Generated by Django 3.1.4 on 2021-01-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210113_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_type',
            old_name='protein',
            new_name='pr',
        ),
    ]
