# Generated by Django 3.1.4 on 2021-01-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210113_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffee',
            new_name='Food',
        ),
    ]
