# Generated by Django 3.1.4 on 2021-01-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_eat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_eat',
            name='en_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_eat',
            name='tc_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
