# Generated by Django 3.1.4 on 2021-02-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210115_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
